let cardValue = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15", "r16", "r17", "r18",]
var card1Value = cardValue[i]
    var card2Value = 0
    var card3Value = 0
    var card4Value = 0
    var card5Value = 0
    var card6Value = 0
    var card7Value = 0
    var card8Value = 0
    var card9Value = 0
    var card10Value = 0
    var card11Value = 0
    var card12Value = 0
    var card13Value = 0
    var card14Value = 0
    var card15Value = 0
    var card16Value = 0
    var card17Value = 0
    var card18Value = 0
    var card19Value = 0
    var card20Value = 0
    var card21Value = 0
    var card22Value = 0
    var card23Value = 0
    var card24Value = 0
    var card25Value = 0
    var card26Value = 0
    var card27Value = 0
    var card28Value = 0
    var card29Value = 0
    var card30Value = 0
    var card31Value = 0
    var card32Value = 0
    var card33Value = 0
    var card34Value = 0
    var card35Value = 0
    var card36Value = 0
function randomizer() {
    let i = parseInt(Math.floor(Math.random() * 36) + 1)
    console.log(i)
    card1Value = cardValue[i]
    card2Value = cardValue[i]
    card3Value = cardValue[i]
    card4Value = cardValue[i]
    card5Value = cardValue[i]
    card6Value = cardValue[i]
    card7Value = cardValue[i]
    card8Value = cardValue[i]
    card9Value = cardValue[i]
    card10Value = cardValue[i]
    card11Value = cardValue[i]
    card12Value = cardValue[i]
    card13Value = cardValue[i]
    card14Value = cardValue[i]
    card15Value = cardValue[i]
    card16Value = cardValue[i]
    card17Value = cardValue[i]
    card18Value = cardValue[i]
    card19Value = cardValue[i]
    card20Value = cardValue[i]
    card21Value = cardValue[i]
    card22Value = cardValue[i]
    card23Value = cardValue[i]
    card24Value = cardValue[i]
    card25Value = cardValue[i]
    card26Value = cardValue[i]
    card27Value = cardValue[i]
    card28Value = cardValue[i]
    card29Value = cardValue[i]
    card30Value = cardValue[i]
    card31Value = cardValue[i]
    card32Value = cardValue[i]
    card33Value = cardValue[i]
    card34Value = cardValue[i]
    card35Value = cardValue[i]
    card36Value = cardValue[i]
}
function flipCard1() {
    //source = https://www.w3schools.com/JSREF/prop_pushbutton_value.asp
    document.getElementById("card1").value = "2 + 2"
}
function flipCard2() {
    document.getElementById("card2").value = 4
}